/* Map arduino pin names to atmega ports */

#define A0_PIN      DDC0
#define A1_PIN      DDC1
#define A2_PIN      DDC2
#define A3_PIN      DDC3
#define A4_PIN      DDC4
#define A5_PIN      DDC5
#define A0_PORT     PORTC
#define A1_PORT     PORTC
#define A2_PORT     PORTC
#define A3_PORT     PORTC
#define A4_PORT     PORTC
#define A5_PORT     PORTC
#define A0_INP      PINC
#define A1_INP      PINC
#define A2_INP      PINC
#define A3_INP      PINC
#define A4_INP      PINC
#define A5_INP      PINC

#define RXI_PIN     DDD0
#define TX0_PIN     DDD1
#define D2_PIN      DDD2
#define D3_PIN      DDD3
#define D4_PIN      DDD4
#define D5_PIN      DDD5
#define D6_PIN      DDD6
#define D7_PIN      DDD7
#define RXI_PORT     PORTD
#define TX0_PORT     PORTD
#define D2_PORT      PORTD
#define D3_PORT      PORTD
#define D4_PORT      PORTD
#define D5_PORT      PORTD
#define D6_PORT      PORTD
#define D7_PORT      PORTD
#define RXI_INP     PIND
#define TX0_INP     PIND
#define D2_INP      PIND
#define D3_INP      PIND
#define D4_INP      PIND
#define D5_INP      PIND
#define D6_INP      PIND
#define D7_INP      PIND

#define D8_PIN      DDB0
#define D9_PIN      DDB1
#define D10_PIN     DDB2
#define MOSI_PIN    DDB3
#define MISO_PIN    DDB4
#define SCK_PIN     DDB5
#define D8_PORT      PORTB
#define D9_PORT      PORTB
#define D10_PORT     PORTB
#define MOSI_PORT    PORTB
#define MISO_PORT    PORTB
#define SCK_PORT     PORTB
#define D8_INP      PINB
#define D9_INP      PINB
#define D10_INP     PINB
#define MOSI_INP    PINB
#define MISO_INP    PINB
#define SCK_INP     PINB

